In [ ]:
#import libraries
import pandas as pd

In [ ]:
#import dataset
df=pd.read_csv('../data/raw/train.csv')

In [ ]:
#1- dataset diemensions(size)--check the no of rows and cols
df.shape

(58592, 44)

In [ ]:
#2- dataset preview--inspect first few rows to understand the srtructure and values of the dataset
df.head()

,policy_id,policy_tenure,age_of_car,age_of_policyholder,area_cluster,population_density,make,segment,model,fuel_type,...,is_brake_assist,is_power_door_locks,is_central_locking,is_power_steering,is_driver_seat_height_adjustable,is_day_night_rear_view_mirror,is_ecw,is_speed_alert,ncap_rating,is_claim
0,ID00001,0.515874,0.05,0.644231,C1,4990,1,A,M1,CNG,...,No,No,No,Yes,No,No,No,Yes,0,0
1,ID00002,0.672619,0.02,0.375000,C2,27003,1,A,M1,CNG,...,No,No,No,Yes,No,No,No,Yes,0,0
2,ID00003,0.841110,0.02,0.384615,C3,4076,1,A,M1,CNG,...,No,No,No,Yes,No,No,No,Yes,0,0
3,ID00004,0.900277,0.11,0.432692,C4,21622,1,C1,M2,Petrol,...,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,2,0
4,ID00005,0.596403,0.11,0.634615,C5,34738,2,A,M3,Petrol,...,No,Yes,Yes,Yes,No,Yes,Yes,Yes,2,0

In [8]:
#3- dataset information --check data types and non-null values of each col
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 58592 entries, 0 to 58591
Data columns (total 44 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   policy_id                         58592 non-null  str
 1   policy_tenure                     58592 non-null  float64
 2   age_of_car                        58592 non-null  float64
 3   age_of_policyholder               58592 non-null  float64
 4   area_cluster                      58592 non-null  str
 5   population_density                58592 non-null  int64
 6   make                              58592 non-null  int64
 7   segment                           58592 non-null  str
 8   model                             58592 non-null  str
 9   fuel_type                         58592 non-null  str
 10  max_torque                        58592 non-null  str
 11  max_power                         58592 non-null  str
 12  engine_type                       58592 non-null  str
 13  airbags                           58592 non-null  int64
 14  is_esc                            58592 non-null  str
 15  is_adjustable_steering            58592 non-null  str
 16  is_tpms                           58592 non-null  str
 17  is_parking_sensors                58592 non-null  str
 18  is_parking_camera                 58592 non-null  str
 19  rear_brakes_type                  58592 non-null  str
 20  displacement                      58592 non-null  int64
 21  cylinder                          58592 non-null  int64
 22  transmission_type                 58592 non-null  str
 23  gear_box                          58592 non-null  int64
 24  steering_type                     58592 non-null  str
 25  turning_radius                    58592 non-null  float64
 26  length                            58592 non-null  int64
 27  width                             58592 non-null  int64
 28  height                            58592 non-null  int64
 29  gross_weight                      58592 non-null  int64
 30  is_front_fog_lights               58592 non-null  str
 31  is_rear_window_wiper              58592 non-null  str
 32  is_rear_window_washer             58592 non-null  str
 33  is_rear_window_defogger           58592 non-null  str
 34  is_brake_assist                   58592 non-null  str
 35  is_power_door_locks               58592 non-null  str
 36  is_central_locking                58592 non-null  str
 37  is_power_steering                 58592 non-null  str
 38  is_driver_seat_height_adjustable  58592 non-null  str
 39  is_day_night_rear_view_mirror     58592 non-null  str
 40  is_ecw                            58592 non-null  str
 41  is_speed_alert                    58592 non-null  str
 42  ncap_rating                       58592 non-null  int64
 43  is_claim                          58592 non-null  int64
dtypes: float64(4), int64(12), str(28)
memory usage: 19.7 MB

In [ ]:
#4- check missing values 
df.isnull().sum()

policy_id                           0
policy_tenure                       0
age_of_car                          0
age_of_policyholder                 0
area_cluster                        0
population_density                  0
make                                0
segment                             0
model                               0
fuel_type                           0
max_torque                          0
max_power                           0
engine_type                         0
airbags                             0
is_esc                              0
is_adjustable_steering              0
is_tpms                             0
is_parking_sensors                  0
is_parking_camera                   0
rear_brakes_type                    0
displacement                        0
cylinder                            0
transmission_type                   0
gear_box                            0
steering_type                       0
turning_radius                      0
length                              0
width                               0
height                              0
gross_weight                        0
is_front_fog_lights                 0
is_rear_window_wiper                0
is_rear_window_washer               0
is_rear_window_defogger             0
is_brake_assist                     0
is_power_door_locks                 0
is_central_locking                  0
is_power_steering                   0
is_driver_seat_height_adjustable    0
is_day_night_rear_view_mirror       0
is_ecw                              0
is_speed_alert                      0
ncap_rating                         0
is_claim                            0
dtype: int64

In [15]:
#5- duplicate records(rows)
df.duplicated().sum()

np.int64(0)

In [16]:
#6- target variable distribution
df['is_claim'].value_counts()

is_claim
0    54844
1     3748
Name: count, dtype: int64

Observation-
The target variable is imabalanced, with most records belonging to the non-claim class.

In [ ]:
#7. data type distribution-check how many data types cols have.
df.dtypes.value_counts()

str        28
int64      12
float64     4
Name: count, dtype: int64

In [21]:
#8. Numerical and Categorical Features--identify numerical and categorical features in the dataset

numerical_features=df.select_dtypes(include=['int64','float64']).columns
categorical_features=df.select_dtypes(include=['str']).columns
print('Numerical Features:')
print(numerical_features)
print('Categorical Features:')
print(categorical_features)

Numerical Features:
Index(['policy_tenure', 'age_of_car', 'age_of_policyholder',
       'population_density', 'make', 'airbags', 'displacement', 'cylinder',
       'gear_box', 'turning_radius', 'length', 'width', 'height',
       'gross_weight', 'ncap_rating', 'is_claim'],
      dtype='str')
Categorical Features:
Index(['policy_id', 'area_cluster', 'segment', 'model', 'fuel_type',
       'max_torque', 'max_power', 'engine_type', 'is_esc',
       'is_adjustable_steering', 'is_tpms', 'is_parking_sensors',
       'is_parking_camera', 'rear_brakes_type', 'transmission_type',
       'steering_type', 'is_front_fog_lights', 'is_rear_window_wiper',
       'is_rear_window_washer', 'is_rear_window_defogger', 'is_brake_assist',
       'is_power_door_locks', 'is_central_locking', 'is_power_steering',
       'is_driver_seat_height_adjustable', 'is_day_night_rear_view_mirror',
       'is_ecw', 'is_speed_alert'],
      dtype='str')

In [ ]:
#9. Unique values in categorical features-check how many categories each categorical feature contains
df[categorical_features].nunique().sort_values(ascending=True)

is_parking_sensors                      2
transmission_type                       2
rear_brakes_type                        2
is_parking_camera                       2
is_adjustable_steering                  2
is_tpms                                 2
is_esc                                  2
is_driver_seat_height_adjustable        2
is_power_steering                       2
is_central_locking                      2
is_power_door_locks                     2
is_brake_assist                         2
is_rear_window_defogger                 2
is_rear_window_washer                   2
is_rear_window_wiper                    2
is_front_fog_lights                     2
is_ecw                                  2
is_day_night_rear_view_mirror           2
is_speed_alert                          2
fuel_type                               3
steering_type                           3
segment                                 6
max_torque                              9
max_power                               9
model                                  11
engine_type                            11
area_cluster                           22
policy_id                           58592
dtype: int64

In [23]:
#10. numerical feature statistics- analyze basic stats
df.describe()

,policy_tenure,age_of_car,age_of_policyholder,population_density,make,airbags,displacement,cylinder,gear_box,turning_radius,length,width,height,gross_weight,ncap_rating,is_claim
count,58592.000000,58592.000000,58592.000000,58592.000000,58592.000000,58592.000000,58592.000000,58592.000000,58592.000000,58592.000000,58592.000000,58592.000000,58592.00000,58592.000000,58592.000000,58592.000000
mean,0.611246,0.069424,0.469420,18826.858667,1.763722,3.137066,1162.355851,3.626963,5.245443,4.852893,3850.476891,1672.233667,1553.33537,1385.276813,1.759950,0.063968
std,0.414156,0.056721,0.122886,17660.174792,1.136988,1.832641,266.304786,0.483616,0.430353,0.228061,311.457119,112.089135,79.62227,212.423085,1.389576,0.244698
min,0.002735,0.000000,0.288462,290.000000,1.000000,1.000000,796.000000,3.000000,5.000000,4.500000,3445.000000,1475.000000,1475.00000,1051.000000,0.000000,0.000000
25%,0.210250,0.020000,0.365385,6112.000000,1.000000,2.000000,796.000000,3.000000,5.000000,4.600000,3445.000000,1515.000000,1475.00000,1185.000000,0.000000,0.000000
50%,0.573792,0.060000,0.451923,8794.000000,1.000000,2.000000,1197.000000,4.000000,5.000000,4.800000,3845.000000,1735.000000,1530.00000,1335.000000,2.000000,0.000000
75%,1.039104,0.110000,0.548077,27003.000000,3.000000,6.000000,1493.000000,4.000000,5.000000,5.000000,3995.000000,1755.000000,1635.00000,1510.000000,3.000000,0.000000
max,1.396641,1.000000,1.000000,73430.000000,5.000000,6.000000,1498.000000,4.000000,6.000000,5.200000,4300.000000,1811.000000,1825.00000,1720.000000,5.000000,1.000000

In [24]:
#11. inspect categorical values- check which col has with categories
for col in categorical_features:
    if col!='policy_id':
        print(f"\n {col}")
        print(df[col].unique())

 area_cluster
<StringArray>
[ 'C1',  'C2',  'C3',  'C4',  'C5',  'C6',  'C7',  'C8',  'C9', 'C10', 'C11',
 'C12', 'C13', 'C14', 'C15', 'C16', 'C17', 'C18', 'C19', 'C20', 'C21', 'C22']
Length: 22, dtype: str

 segment
<StringArray>
['A', 'C1', 'C2', 'B2', 'B1', 'Utility']
Length: 6, dtype: str

 model
<StringArray>
['M1', 'M2', 'M3', 'M4', 'M5', 'M6', 'M7', 'M8', 'M9', 'M10', 'M11']
Length: 11, dtype: str

 fuel_type
<StringArray>
['CNG', 'Petrol', 'Diesel']
Length: 3, dtype: str

 max_torque
<StringArray>
[  '60Nm@3500rpm',  '113Nm@4400rpm',   '91Nm@4250rpm',  '250Nm@2750rpm',
  '200Nm@3000rpm', '82.1Nm@3400rpm',  '200Nm@1750rpm',   '85Nm@3000rpm',
  '170Nm@4000rpm']
Length: 9, dtype: str

 max_power
<StringArray>
[ '40.36bhp@6000rpm',  '88.50bhp@6000rpm',  '67.06bhp@5500rpm',
 '113.45bhp@4000rpm',  '88.77bhp@4000rpm',  '55.92bhp@5300rpm',
  '97.89bhp@3600rpm',  '61.68bhp@6000rpm', '118.36bhp@5500rpm']
Length: 9, dtype: str

 engine_type
<StringArray>
[        'F8D Petrol Engine',        '1.2 L K12N Dualjet',
                   '1.0 SCe',             '1.5 L U2 CRDi',
 '1.5 Turbocharged Revotorq',         'K Series Dual jet',
     '1.2 L K Series Engine',                      'K10C',
                    'i-DTEC',                      'G12B',
 '1.5 Turbocharged Revotron']
Length: 11, dtype: str

 is_esc
<StringArray>
['No', 'Yes']
Length: 2, dtype: str

 is_adjustable_steering
<StringArray>
['No', 'Yes']
Length: 2, dtype: str

 is_tpms
<StringArray>
['No', 'Yes']
Length: 2, dtype: str

 is_parking_sensors
<StringArray>
['Yes', 'No']
Length: 2, dtype: str

 is_parking_camera
<StringArray>
['No', 'Yes']
Length: 2, dtype: str

 rear_brakes_type
<StringArray>
['Drum', 'Disc']
Length: 2, dtype: str

 transmission_type
<StringArray>
['Manual', 'Automatic']
Length: 2, dtype: str

 steering_type
<StringArray>
['Power', 'Electric', 'Manual']
Length: 3, dtype: str

 is_front_fog_lights
<StringArray>
['No', 'Yes']
Length: 2, dtype: str

 is_rear_window_wiper
<StringArray>
['No', 'Yes']
Length: 2, dtype: str

 is_rear_window_washer
<StringArray>
['No', 'Yes']
Length: 2, dtype: str

 is_rear_window_defogger
<StringArray>
['No', 'Yes']
Length: 2, dtype: str

 is_brake_assist
<StringArray>
['No', 'Yes']
Length: 2, dtype: str

 is_power_door_locks
<StringArray>
['No', 'Yes']
Length: 2, dtype: str

 is_central_locking
<StringArray>
['No', 'Yes']
Length: 2, dtype: str

 is_power_steering
<StringArray>
['Yes', 'No']
Length: 2, dtype: str

 is_driver_seat_height_adjustable
<StringArray>
['No', 'Yes']
Length: 2, dtype: str

 is_day_night_rear_view_mirror
<StringArray>
['No', 'Yes']
Length: 2, dtype: str

 is_ecw
<StringArray>
['No', 'Yes']
Length: 2, dtype: str

 is_speed_alert
<StringArray>
['Yes', 'No']
Length: 2, dtype: str

In [27]:
#12. seperate target and features
X=df.drop(columns=["is_claim"])
Y=df["is_claim"]
print("Features Shape",X.shape)
print("Target Shape",Y.shape)

Features Shape (58592, 43)
Target Shape (58592,)

In [28]:
#13 . check constant features
constant_features=X.columns[X.nunique()==1]
print('Constant Features', constant_features)

Constant Features Index([], dtype='str')